namespace Darp.Ble.Hci.AssignedNumbers;

/// <summary>
/// The CoreVersion.
/// This enum was autogenerated on 01/03/2025
/// </summary>
[System.Diagnostics.CodeAnalysis.SuppressMessage("ReSharper", "InconsistentNaming")]
public enum CoreVersion : byte
{
    /// <summary> Bluetooth® Core Specification 1.0b (Withdrawn) </summary>
    BluetoothCoreSpecification10B = 0x00,

    /// <summary> Bluetooth® Core Specification 1.1 (Withdrawn) </summary>
    BluetoothCoreSpecification11 = 0x01,

    /// <summary> Bluetooth® Core Specification 1.2 (Withdrawn) </summary>
    BluetoothCoreSpecification12 = 0x02,

    /// <summary> Bluetooth® Core Specification 2.0+EDR (Withdrawn) </summary>
    BluetoothCoreSpecification20Edr = 0x03,

    /// <summary> Bluetooth® Core Specification 2.1+EDR (Withdrawn) </summary>
    BluetoothCoreSpecification21Edr = 0x04,

    /// <summary> Bluetooth® Core Specification 3.0+HS (Withdrawn) </summary>
    BluetoothCoreSpecification30Hs = 0x05,

    /// <summary> Bluetooth® Core Specification 4.0 (Withdrawn) </summary>
    BluetoothCoreSpecification40 = 0x06,

    /// <summary> Bluetooth® Core Specification 4.1 (Deprecated) </summary>
    BluetoothCoreSpecification41 = 0x07,

    /// <summary> Bluetooth® Core Specification 4.2 </summary>
    BluetoothCoreSpecification42 = 0x08,

    /// <summary> Bluetooth® Core Specification 5.0 </summary>
    BluetoothCoreSpecification50 = 0x09,

    /// <summary> Bluetooth® Core Specification 5.1 </summary>
    BluetoothCoreSpecification51 = 0x0A,

    /// <summary> Bluetooth® Core Specification 5.2 </summary>
    BluetoothCoreSpecification52 = 0x0B,

    /// <summary> Bluetooth® Core Specification 5.3 </summary>
    BluetoothCoreSpecification53 = 0x0C,

    /// <summary> Bluetooth® Core Specification 5.4 </summary>
    BluetoothCoreSpecification54 = 0x0D,

    /// <summary> Bluetooth® Core Specification 6.0 </summary>
    BluetoothCoreSpecification60 = 0x0E,
}
