# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Install workloads
        run: |
          dotnet workload install android

      - name: Restore dependencies
        run:  dotnet restore --configuration Release
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release

      - name: Get git tag
        if: startsWith(github.ref, 'refs/tags')
        uses: little-core-labs/get-git-tag@v3.0.2
      - name: Pack
        if: startsWith(github.ref, 'refs/tags')
        run: |
          for file_name in ./src/**/*.csproj; do
            dotnet pack $file_name --configuration Release --no-restore /p:Version=${GIT_TAG_NAME:1}
          done
      - name: Push to nuget.org
        if: startsWith(github.ref, 'refs/tags')
        run: |
          for pkg_name in ./src/**/bin/Release/*.nupkg; do
            dotnet nuget push $pkg_name --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          done