# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install workloads
        run: |
          dotnet workload install android
      - name: Build and Test
        run: dotnet test --configuration Release
  publish:
    runs-on: ubuntu-latest
    needs: [build-test]
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v4
      - name: Get git tag
        id: tagName
        uses: little-core-labs/get-git-tag@v3.0.2
      - name: Pack
        run: |
          for file_name in ./src/**/*.csproj; do
            echo $file_name
            dotnet pack $file_name --configuration Release --no-restore /p:Version=$GIT_TAG_NAME
          done
      - name: Push
        run: |
          for d in ./src/**/*.csproj ; do \
            dotnet nuget push "$d" --configuration Release /p:Version=${{ steps.tagName.outputs.tag }} \
          done